name: characters_package
description: A Very Good Project created by Very Good CLI.
version: 1.2.1
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: 3.3.10

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  core:
    path: ../core
  dio: ^5.0.0
  hive: ^2.2.3

dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
